[package]
name = "neonvk"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "^0.4.0" }
profiling = { version = "^1.0.0", features = ["profile-with-tracy"] }
thiserror = { version = "^1.0.0" }
ash = { version = "^0.32.0" }
ash-window = { version = "^0.6.0" }
raw-window-handle = { version = "^0.3.0" }
shaders = { path = "shaders" }
vk-mem = { version = "^0.2.0" }
ultraviolet = { version = "^0.8.0" }
miniserde = { version = "^0.1.0" }

# TODO: Move anyhow, sdl2, profiling/profile-with-tracy, png, bytemuck to dev deps
# Currently it's just more ergonomic to have the sandbox in src/bin rather than examples.
sdl2 = { version = "^0.34.0", features = ["raw-window-handle"] }
anyhow = { version = "^1.0.0" }
png = { version = "^0.16.0" }
bytemuck = { version = "^1.7.0" }
