[package]
name = "neonvk"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
profiling = { version = "1.0" }
thiserror = { version = "1.0" }
ash = { version = "0.32" }
ash-window = { version = "0.6" }
raw-window-handle = { version = "0.3" }
shaders = { path = "shaders" }
glam = { version = "0.19" }
miniserde = { version = "0.1" }
bytemuck = { version = "1.7" }
typed-arena = { version = "2.0" }

# TODO: Move anyhow, sdl2, profiling/profile-with-tracy to dev deps
# Currently it's just more ergonomic to have the sandbox in src/bin rather than examples.
sdl2 = { version = "0.34", features = ["raw-window-handle"] }
anyhow = { version = "1.0" }

[profile.dev.package.miniserde]
opt-level = 3

[features]
profile-with-tracy = ["profiling/profile-with-tracy"]
vulkan-validation = ["shaders/generate-debug-info"]
