[package]
name = "neonvk"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "0.4" }
profiling = { version = "1.0" }
thiserror = { version = "1.0" }
ash = { version = "0.37", default-features = false, features = ["linked", "debug"] }
ash-window = { version = "0.10" }
raw-window-handle = { version = "0.3.4" }
shaders = { path = "shaders" }
glam = { version = "0.19", features = ["bytemuck"] }
serde = { version = "1.0" }
serde_derive = { version = "1.0" }
serde_json = { version = "1.0" }
bytemuck = { version = "1.7" }
typed-arena = { version = "2.0" }
once_cell = { version = "1.9" }
memmap2 = { version = "0.5" }

# TODO(cleanup): Move anyhow, sdl2 to dev deps
# Currently it's just more ergonomic to have the sandbox in src/bin rather than examples.
sdl2 = { version = "0.34", features = ["raw-window-handle"] }
anyhow = { version = "1.0" }

[features]
profile-with-tracy = ["profiling/profile-with-tracy"]
profile-with-tracing = ["profiling/profile-with-tracing"]
vulkan-validation = ["shaders/generate-debug-info"]
