[package]
name = "neonvk"
version = "0.1.0"
edition = "2018"

[dependencies]
log = { version = "^0.4.0" }
profiling = { version = "^1.0.0" }
sdl2 = { version = "^0.34.0", features = ["static-link", "bundled"] }
