name: Build
on: [push]

jobs:
  build-linux:
    runs-on: linux-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo build --target x86_64-unknown-linux-gnu
  build-windows:
    runs-on: windows-x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo build --target x86_64-pc-windows-msvc
